{
    "title":"Sports Dark",
    "pipeline":[
        { "name":"fork" },

        { "name":"previous" },
        { "name":"fork" },
        { "name":"shift" },
        { "name":"previous" },
        { "name":"fork" },
        { "name":"shift" },
        { "name":"previous" },
        { "name":"fork" },
        { "name":"shift" },
        { "name":"previous" },
        { "name":"fork" },
        { "name":"shift" },
        { "name":"previous" },
        { "name":"fork" },
        { "name":"shift" },
        { "name":"previous" },
        { "name":"fork" },
        { "name":"shift" },
        { "name":"previous" },
        { "name":"fork" },
        { "name":"shift" },

        { "name":"darken" },
        { "name":"darken" },
        { "name":"darken" },
        { "name":"darken" },
        { "name":"darken" },
        { "name":"darken" },
        { "name":"darken" },
    ]
}
